- name: Demo on Error handling
  hosts: localhost
  tasks:
    - name: Some shell command
      ansible.builtin.shell: ls
      ignore_errors: yes

    - name: Print Hello
      ansible.builtin.debug:
        msg: Hello

