- name: Demo on Filters
  hosts: localhost
  tasks:
    - name: Run uptime command
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print No of Users Logged in
      ansible.builtin.debug:
        msg: "{{ ((OUT.stdout | split(','))[1] |split(' '))[2] | int }}"





